services:
  agent-zero:
    container_name: agent-zero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: development
    image: agent-zero-run:local
    volumes:
      - ./agent-zero:/a0
      - /mypool/agent-zero-data/memory:/a0/memory
      - /mypool/agent-zero-root:/root
    ports:
      - "50080:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
