services:
  agent-zero:
    build:
      context: .
      dockerfile: Dockerfile.vanilla
      args:
        - BRANCH=development
    image: agent-zero-run:vanilla
    container_name: agent-zero-vanilla
    restart: unless-stopped
    ports:
      - "50080:50080"
    volumes:
      - /mypool/agent-zero-data:/data
    environment:
      - DATA_DIR=/data
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
