services:
  agent-zero:
    container_name: agent-zero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: development
    image: agent-zero-run:local
    volumes:
      - /mypool/agent-zero-data:/a0
    ports:
      - "50080:80"

