version: "3.8"
services:
  agent-zero:
    build:
      context: ../..
      dockerfile: docker/myrun/Dockerfile
    image: agent-zero-run:local
    container_name: agent-zero
    ports:
      - "50080:80"
    volumes:
      - /mypool/agent-zero-data:/a0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
